config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  get 'welcome/index'

  resources :cuisines
  resources :areas
  resources :restraunts do
    resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restraunt
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
end

app/models/restraunt.rb
class Restraunt < ApplicationRecord

  validates :title, presence: true
  validates :address, presence: true
  validates :image_url, presence: true

  belongs_to :cuisine
  has_many :comments, :dependent => :destroy

  def self.search(q, qa)
    if q
      where('lower(title) LIKE ? AND lower(address) LIKE ?', "%#{q.downcase}%", "%#{qa.downcase}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, confirmation: true, uniqueness: true
  validates :email_confirmation, presence: true
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password
  has_many :comments, :dependent => :destroy

  def name
    [first_name, last_name].join " "
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate
    if !logged_in?
      redirect_to login_path
    end
  end

  private
  def is_curator?
    curator = User.find(session[:user_id]).curator if session[:user_id]
  end

  def logged_in?
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :logged_in?
  helper_method :is_curator?
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate, except: [:show, :index]

  def show
    @area = Area.find(params[:id])
  end

  def new
  end

  def create
    @area = Area.new(params.require(:area).permit(
    :city,
    :area
    ))

    @area.save
    redirect_to @area
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate

  def create
    @restraunt = Restraunt.find(params[:restraunt_id])
    @comment = @restraunt.comments.build(comment_params)
    @comment.user = current_user

    @comment.save
    redirect_to @restraunt
  end

  def destroy
    @restraunt = Restraunt.find(params[:restraunt_id])
    @comment = @restraunt.comments.find(params[:id])

    @comment.destroy
    redirect_to @restraunt
  end

  private
  def current_user
    current_user = User.find(session[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :authenticate, except: [:show, :index]

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
  end

  def create
    @cuisine = Cuisine.new(params.require(:cuisine).permit(:cname))

    @cuisine.save
    redirect_to @cuisine
  end
end

app/controllers/restraunts_controller.rb
class RestrauntsController < ApplicationController
  before_action :authenticate, except: [:show, :index]

  def index
    @restraunts = Restraunt.search(params[:q], params[:qa])
  end

  def show
    @restraunt = Restraunt.find(params[:id])
  end

  def new
  end

  def edit
    @restraunt = Restraunt.find(params[:id])
  end

  def create
    @restraunt = Restraunt.new(restraunt_params)

    @restraunt.save
    redirect_to @restraunt
  end

  def update
    @restraunt = Restraunt.find(params[:id])

    if @restraunt.update(restraunt_params)
      redirect_to @restraunt
    else
      render 'edit'
    end
  end

  def destroy
    @restraunt = Restraunt.find(params[:id])
    @restraunt.destroy

  end

  private

  def restraunt_params
    params.require(:restraunt).permit(
    :title,
    :cuisine_id,
    :phone,
    :address,
    :cost,
    :heads,
    :image_url
    )
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_restraunt_url, notice: 'Logged In!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_restraunt_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :email,
    :email_confirmation,
    :password
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/restraunts_helper.rb
module RestrauntsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/areas/new.html.erb
<%= render 'layouts/navalt' %>
<h1>Add an area</h1>
<%= form_for :area, url: areas_path do |f| %>
<p>
  <%= f.label :city %>
  <%= f.text_field :city %>
</p>
<p>
  <%= f.label :area %>
  <%= f.text_field :area %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/areas/show.html.erb
<%= render 'layouts/navalt' %>
<p>
  <strong>City:</strong>
  <%= @area.city %>
</p>
<p>
  <strong>Area:</strong>
  <%= @area.area %>
</p>

app/views/comments/_comment.html.erb
<div class="comment">
  <div class="content">
    <a class="author">
      <%= comment.user.first_name + ' ' + comment.user.last_name %>
    </a>
    <div class="text"><%= comment.body %></div>
  </div>
</div>
  <!-- <p><%= link_to "Delete Comment", [comment.restraunt, comment],
          :confirm => 'Are you sure?',
          :method => :delete %> -->

app/views/comments/_form.html.erb
<div class="comments">

  <div class="ui basic segment">
    <div class="ui comments">
      <h3 class="ui dividing header">Comments</h3>
      <%= render @restraunt.comments %>
    </div>
  </div>
  <% if logged_in? %>
  <div class="ui basic segment">
    <%= form_for([@restraunt, @restraunt.comments.build], :html => {:class=>'ui reply form'}) do |f| %>
      <div class="field">
        <%= f.text_area :body, :required => true%>
      </div>
      <%= f.submit :class => 'ui blue submit button' %>
    <% end %>
  </div>
  <% else %>
    <div class="ui basic segment">
      <a href="/login" class="positive ui button">Sign In To Comment</a>
    </div>
  <% end %>
</div>

app/views/cuisines/new.html.erb
<%= render 'layouts/navalt' %>
<h1>Add a new cuisine</h1>
<%= form_for :cuisine, url: cuisines_path do |f| %>
  <p>
    <%= f.label :cname %>
    <%= f.text_field :cname %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/cuisines/show.html.erb
<%= render 'layouts/navalt' %>
<p>
  <strong>Cuisine:</strong>
  <%= @cuisine.cname %>
</p>

app/views/restraunts/edit.html.erb
<%= render 'layouts/navalt' %>
<h1>Edit a restraunt</h1>
<%= form_for @restraunt do |f| %>
<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :cuisine %>
  <%= f.select :cuisine_id, options_for_select(Cuisine.all.map{|c|[c.cname, c.id]}) %>
</p>
<p>
  <%= f.label :phone %>
  <%= f.telephone_field :phone %>
</p>
<p>
  <%= f.label :address %>
  <%= f.text_area :address %>
</p>
<p>
  <%= f.label :cost %>
  <%= f.number_field :cost %>
</p>
<p>
  <%= f.label :heads %>
  <%= f.number_field :heads %>
</p>
<p>
  <%= f.label :image_url %>
  <%= f.text_field :image_url %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

app/views/restraunts/index.html.erb
<%= render 'layouts/navbar' %>
<div class="ui stackable centered grid">

<% @restraunts.each do |restraunt| %>

    <div class="row">
    <div class="eight wide column">

        <div class="ui fluid raised card">
          <div class="image">
            <%= image_tag restraunt.image_url %>
          </div>
          <div class="content">
            <div class="header"><%= restraunt.title %></div>
            <%= restraunt.cuisine.cname %>
          </div>
          <div class="extra content">
            <div class="ui two buttons">
              <%= link_to 'View Restraunt', restraunt_path(restraunt), :class=>"ui basic black button" %>
              <a href="tel:<%= restraunt.phone %>" class="ui basic green button">Phone Up</a>
            </div>
          </div>
          <div class="extra content">
              &#8377;<%= restraunt.cost %> for <%= restraunt.heads %> people.
          </div>
        </div>

    </div>
  </div>
  <!-- <div class="restraunt">
    <div class="rest-img">

      <h3 class="rest-name"> <%= restraunt.title %> </h3>
      <h4 class="rest-type"> <%= restraunt.cuisine.cname %></h4>
      <h4 class="rest-rating"> 0.0 </h4>
    </div>
    <div class="rest-content">
      <div>
        <p><span class="rest-d">Cuisine:</span><%= restraunt.cuisine.cname %></p>
        <p><span class="rest-d">For <%= restraunt.heads %> people:</span>&#8377;<%= restraunt.cost %></p>
      </div>

      <%= link_to 'View Restraunt', restraunt_path(restraunt), :class=>"button" %>
      <a href="tel:<%= restraunt.phone %>" class="button btn-white">Phone Up</a>
    </div>
  </div> -->
<% end %>
</div>

app/views/restraunts/new.html.erb
<%= render 'layouts/navalt' %>
<% if is_curator? %>
  <h1 class="ui center aligned header">Add a new restraunt</h1>
  <div class="ui centered stackable grid">
    <div class="four wide column">
      <%= form_for :restraunt, :html=>{:class=>"ui form"}, url: restraunts_path do |f| %>
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, :required => true %>
      </div>
      <div class="field">
        <%= f.label :cuisine %>
        <%= f.select :cuisine_id, options_for_select(Cuisine.all.map{|c|[c.cname, c.id]}) %>
      </div>
      <div class="field">
        <%= f.label :phone %>
        <%= f.telephone_field :phone, :required => true%>
      </div>
      <div class="field">
        <%= f.label :address %>
        <%= f.text_area :address, :required => true %>
      </div>
      <div class="field">
        <%= f.label :cost %>
        <%= f.number_field :cost, :required => true %>
      </div>
      <div class="field">
        <%= f.label :heads %>
        <%= f.number_field :heads, :required => true %>
      </div>
      <div class="field">
        <%= f.label :image_url %>
        <%= f.text_field :image_url, :required => true %>
      </div>

      <%= f.submit :class=>"ui fluid button" %>

      <% end %>
    </div>
  </div>
<% else %>
  <%= render 'layouts/become_curator' %>
<% end %>

app/views/restraunts/show.html.erb
<%= render 'layouts/navbar' %>

<div class="ui centered stackable grid">
  <div class="eight wide column">
    <div class="ui fluid card">
        <div class="image">
          <div class="ui blue ribbon label">
        <i class="spoon icon"></i> <%= @restraunt.cuisine.cname %>
      </div>
          <%= image_tag @restraunt.image_url %>
        </div>
        <div class="content">
          <a class="header"><%= @restraunt.title %></a>
          <div class="meta">
            <div class="ui tag labels">
              <span class="data"><a class="ui label">&#8377;<%= @restraunt.cost %> for <%= @restraunt.heads%> people</a></span>
            </div>
          </div>
          <div class="ui list">
            <a class="item">
              <i class="phone icon"></i>
              <div class="content">
                <div class="header">Phone</div>
                <div class="description"><%= @restraunt.phone %></div>
              </div>
            </a>
            <a class="item">
              <i class="marker icon"></i>
              <div class="content">
                <div class="header">Address</div>
                <div class="description"><%= @restraunt.address %></div>
              </div>
            </a>
          </div>
        </div>


        
      <%= render 'comments/form' %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'layouts/nav_only_brand' %>
<% if @user.errors.any? %>
  <div class="ui basic segment">
    <div class="ui warning message">
      <i class="close icon"></i>
      <div class="header">
        <% @user.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </div>
    </div>
  </div>
<div id="error">
  <ul>

  </ul>
</div>
<% end %>
<h1 class="ui center aligned header">Sign Up</h1>
<div class="ui centered stackable grid">
  <div class="four wide column">
    <%= form_for @user, :html => {:class=>"ui form"} do |f| %>
      <div class="field">
        <%= f.label :first_name %>
        <%= f.text_field :first_name, :required => true %>
      </div>
      <div class="field">
        <%= f.label :last_name %>
        <%= f.text_field :last_name, :required => true %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, :required => true %>
      </div>
      <div class="field">
        <%= f.label :email_confirmation %>
        <%= f.email_field :email_confirmation, :required => true %>
      </div>
      <div class="field">
        <%= f.label :password %>
        <%= f.password_field :password, :required => true %>
      </div>
      <%= f.submit :class=>"ui fluid button" %>
    <% end %>
  </div>
</div>
<script>
$('.message .close')
  .on('click', function() {
    $(this)
      .closest('.message')
      .transition('fade')
    ;
  })
;
</script>

app/views/welcome/index.html.erb
<%= render 'layouts/navalt' %>

  <div class="ui stackable centered grid">
    <div class="one column row">
      <% if notice %>
      <div class="ui warning message">
        <i class="close icon"></i>
        <div class="header">
          <%= notice %>
        </div>
      </div>
      <% end %>
      <div class="column" style="margin-top:64px;">
        <h2 class="ui center aligned icon header">
          <i class="circular food icon"></i>
          flavr.
          <div class="sub header">Curated fine dining restraunts.</div>
        </h2>

      </div>

    </div>
    <div class="eight wide column">
      <%= form_tag(restraunts_path, method: :get, :class => "ui form") do %>
        <div class="two fields">
          <div class="field">
            <%= select_tag(:qa, options_for_select(Area.select(:city).map(&:city).uniq + Area.all.map{|area| [area.area+', '+area.city, area.area]}), :class => "search-loc") %>
          </div>
          <div class="field">
            <%= text_field_tag :q, params[:q], placeholder: "Search for fine dining anywhere..." %>
          </div>
        </div>
        <%= submit_tag 'Search', name: nil, :class=> "fluid ui black button" %>
      <% end %>
    </div>


  </div>
  <script>
  $('.message .close')
    .on('click', function() {
      $(this)
        .closest('.message')
        .transition('fade')
      ;
    })
  ;
  </script>