config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions
  get 'welcome/index'

  resources :cuisines
  resources :areas
  resources :restraunts do
    resources :comments
  end

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
class Area < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restraunt
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
end

app/models/restraunt.rb
class Restraunt < ApplicationRecord

  validates :title, presence: true
  validates :address, presence: true
  validates :image_url, presence: true

  belongs_to :cuisine
  has_many :comments, :dependent => :destroy

  def self.search(q, qa)
    if q
      where('lower(title) LIKE ? AND lower(address) LIKE ?', "%#{q.downcase}%", "%#{qa.downcase}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, confirmation: true, uniqueness: true
  validates :email_confirmation, presence: true
  validates :password, presence: true, length: { minimum: 8 }

  has_secure_password
  has_many :comments, :dependent => :destroy

  def name
    [first_name, last_name].join " "
  end
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  before_action :authenticate, except: [:show, :index]

  def show
    @area = Area.find(params[:id])
  end

  def new
  end

  def create
    @area = Area.new(params.require(:area).permit(
    :city,
    :area
    ))

    @area.save
    redirect_to @area
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate

  def create
    @restraunt = Restraunt.find(params[:restraunt_id])
    @comment = @restraunt.comments.build(comment_params)
    @comment.user = current_user

    @comment.save
    redirect_to @restraunt
  end

  def destroy
    @restraunt = Restraunt.find(params[:restraunt_id])
    @comment = @restraunt.comments.find(params[:id])

    @comment.destroy
    redirect_to @restraunt
  end

  private
  def current_user
    current_user = User.find(session[:user_id])
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :authenticate, except: [:show, :index]

  def show
    @cuisine = Cuisine.find(params[:id])
  end

  def new
  end

  def create
    @cuisine = Cuisine.new(params.require(:cuisine).permit(:cname))

    @cuisine.save
    redirect_to @cuisine
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to new_restraunt_url, notice: 'Logged In!'
    else
      flash.now.alert = 'Email or password is invalid'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to new_restraunt_url, notice: 'Thank you for signing up!'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(
    :first_name,
    :last_name,
    :email,
    :email_confirmation,
    :password
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/areas_helper.rb
module AreasHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/cuisines_helper.rb
module CuisinesHelper
end

app/helpers/restraunts_helper.rb
module RestrauntsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_become_curator.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular trophy icon"></i>
  Become A Curator
  <div class="sub header">
    Think you've got what it takes to contribute to our list of eateries?
  </div>
  <div class="ui basic segment">
    <div class="ui animated fade button" tabindex="0">
      <div class="visible content">Tell Us Why</div>
      <div class="hidden content">
        <a href="mailto:example@example.com?subject=Flavr%20Curator">Email Us</a>
      </div>
    </div>
  </div>
</h2>

app/views/layouts/_nav_only_brand.html.erb
<div class="ui secondary pointing menu">
  <a href="/" class="active item">
    flavr.
  </a>
</div>

app/views/layouts/_navalt.html.erb
<div class="ui secondary pointing menu">
  <a href="/" class="active item">
    flavr.
  </a>
  <div class="right menu">
    <% if logged_in? %>
      <%= link_to "Sign Out", logout_path, :class => "ui item" %>
    <% else %>
      <%= link_to "Login", login_path, :class => "ui item" %>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="ui secondary pointing menu">
  <a href="/" class="active item">
    flavr.
  </a>

    <div class="right menu">
        <% if logged_in? %>
          <%= link_to "Sign Out", logout_path, :class => "ui item" %>
        <% else %>
          <%= link_to "Login", login_path, :class => "ui item" %>
          <%= link_to "Sign Up", signup_path, :class => "ui item" %>
        <% end %>

    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flavr</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <div class="ui center aligned basic segment">
      Made with <i class="code icon"></i> by <a href="https://laptop64.wordpress.com/">Dylan Dsouza</a>
    </div>
  </body>
</html>